# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerWidget(object):
    def setupUi(self, ManagerWidget):
        ManagerWidget.setObjectName("ManagerWidget")
        ManagerWidget.resize(332, 202)
        self.gridLayoutWidget = QtWidgets.QWidget(ManagerWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.launchAverageDataWindow_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.launchAverageDataWindow_btn.setFont(font)
        self.launchAverageDataWindow_btn.setObjectName("launchAverageDataWindow_btn")
        self.gridLayout.addWidget(self.launchAverageDataWindow_btn, 3, 1, 1, 1)
        self.launchFitDataWindow_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.launchFitDataWindow_btn.setFont(font)
        self.launchFitDataWindow_btn.setObjectName("launchFitDataWindow_btn")
        self.gridLayout.addWidget(self.launchFitDataWindow_btn, 4, 1, 1, 1)
        self.processData_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.processData_btn.setFont(font)
        self.processData_btn.setObjectName("processData_btn")
        self.gridLayout.addWidget(self.processData_btn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 1, 1, 1)
        self.fileRenaming_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fileRenaming_btn.setFont(font)
        self.fileRenaming_btn.setObjectName("fileRenaming_btn")
        self.gridLayout.addWidget(self.fileRenaming_btn, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.launchPlottingWindow_btn = QtWidgets.QPushButton(ManagerWidget)
        self.launchPlottingWindow_btn.setGeometry(QtCore.QRect(110, 210, 121, 31))
        self.launchPlottingWindow_btn.setObjectName("launchPlottingWindow_btn")

        self.retranslateUi(ManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(ManagerWidget)

    def retranslateUi(self, ManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        ManagerWidget.setWindowTitle(_translate("ManagerWidget", "Form"))
        self.launchAverageDataWindow_btn.setText(_translate("ManagerWidget", "Average Data"))
        self.launchFitDataWindow_btn.setText(_translate("ManagerWidget", "Fit Data"))
        self.processData_btn.setText(_translate("ManagerWidget", "Process Raw Data"))
        self.title.setText(_translate("ManagerWidget", "Interactive Friction Model Software Manager"))
        self.fileRenaming_btn.setText(_translate("ManagerWidget", "Rename Files"))
        self.launchPlottingWindow_btn.setText(_translate("ManagerWidget", "Second Window"))
