# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fitting_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FittingWidget(object):
    def setupUi(self, FittingWidget):
        FittingWidget.setObjectName("FittingWidget")
        FittingWidget.resize(362, 136)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(FittingWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(110, 90, 141, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupID_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupID_label.setFont(font)
        self.groupID_label.setObjectName("groupID_label")
        self.gridLayout_3.addWidget(self.groupID_label, 0, 0, 1, 1)
        self.groupID_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupID_spinBox.setFont(font)
        self.groupID_spinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.groupID_spinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.groupID_spinBox.setMinimum(1)
        self.groupID_spinBox.setProperty("value", 1)
        self.groupID_spinBox.setObjectName("groupID_spinBox")
        self.gridLayout_3.addWidget(self.groupID_spinBox, 0, 1, 1, 1)
        self.title = QtWidgets.QLabel(FittingWidget)
        self.title.setGeometry(QtCore.QRect(70, 10, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(FittingWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotResults_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plotResults_btn.setFont(font)
        self.plotResults_btn.setObjectName("plotResults_btn")
        self.horizontalLayout.addWidget(self.plotResults_btn)
        self.manualFitting_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.manualFitting_btn.setFont(font)
        self.manualFitting_btn.setObjectName("manualFitting_btn")
        self.horizontalLayout.addWidget(self.manualFitting_btn)
        self.automaticFitting_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.automaticFitting_btn.setFont(font)
        self.automaticFitting_btn.setObjectName("automaticFitting_btn")
        self.horizontalLayout.addWidget(self.automaticFitting_btn)

        self.retranslateUi(FittingWidget)
        QtCore.QMetaObject.connectSlotsByName(FittingWidget)

    def retranslateUi(self, FittingWidget):
        _translate = QtCore.QCoreApplication.translate
        FittingWidget.setWindowTitle(_translate("FittingWidget", "Form"))
        self.groupID_label.setText(_translate("FittingWidget", "Group ID"))
        self.title.setText(_translate("FittingWidget", "Fitting Friction Model"))
        self.plotResults_btn.setText(_translate("FittingWidget", "Plot Results"))
        self.manualFitting_btn.setText(_translate("FittingWidget", "Manual Fit"))
        self.automaticFitting_btn.setText(_translate("FittingWidget", "Automatic Fit"))
