# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotting_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(745, 606)
        self.plotWidget = MplWidget(Form)
        self.plotWidget.setGeometry(QtCore.QRect(10, 10, 721, 521))
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(420, 550, 309, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotData_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotData_btn.sizePolicy().hasHeightForWidth())
        self.plotData_btn.setSizePolicy(sizePolicy)
        self.plotData_btn.setObjectName("plotData_btn")
        self.horizontalLayout.addWidget(self.plotData_btn)
        self.clearGraph_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clearGraph_btn.setObjectName("clearGraph_btn")
        self.horizontalLayout.addWidget(self.clearGraph_btn)
        self.exit_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(210, 550, 171, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.processData_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.processData_btn.setText("")
        self.processData_btn.setObjectName("processData_btn")
        self.horizontalLayout_2.addWidget(self.processData_btn)
        self.averageData_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.averageData_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageData_btn.sizePolicy().hasHeightForWidth())
        self.averageData_btn.setSizePolicy(sizePolicy)
        self.averageData_btn.setText("")
        self.averageData_btn.setObjectName("averageData_btn")
        self.horizontalLayout_2.addWidget(self.averageData_btn)
        self.changeText_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.changeText_btn.setText("")
        self.changeText_btn.setObjectName("changeText_btn")
        self.horizontalLayout_2.addWidget(self.changeText_btn)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plotData_btn.setText(_translate("Form", "Plot Sample Data"))
        self.clearGraph_btn.setText(_translate("Form", "Clear"))
        self.exit_btn.setText(_translate("Form", "Exit"))
from mplwidget import MplWidget
